### ISSUE TITLE
Multiple Instances

### ISSUE THREAD

**Issue by windischb** [blehnen/DotNetWorkQueue#1]
Hi!

I'm not sure if this library can handle my requirements and i haven't found an answer in the wiki.
So i hope you can answer my Question...

I have two (or more) Windows Services which are running on different Servers.
If i configure all those Services the same, will the Task be executed on only one of those services, or on every service/server?

I want to build a distributed Webservice, which uses a Loadbalancer. So, all Services can create "Messages" but only one of them should execute the Task. At best the one which is idle or is the fastest...

Br
Bernhard

**Comment by blehnen** [comment]
Hi,

The task will only be executed on a single service in the above case.  Both consumers won't de-queue the same message.

**Comment by windischb** [comment]
Ah great!
Many thanks!!
