### ISSUE TITLE
When an object is inserted into the queue with a delay, the operation executes immediately

### ISSUE THREAD

**Issue by tmcque9** [blehnen/DotNetWorkQueue#11]
Here's my code:
```
var data = new AdditionalMessageData();
data.SetDelay(TimeSpan.FromSeconds(120));
await queue.SendAsync(someObject, data);
```

I would expect to see the queue handler execute 120 seconds after the object was inserted, but instead it's executing immediately.  What am I doing wrong?

**Comment by blehnen** [comment]
When you created the queue, did you enable delayed processing?

i.e.

createQueue.Options.EnableDelayedProcessing = true;

**Comment by tmcque9** [comment]
Yes

```
if (!(queueCreator.QueueExists))
				{
					Logger.Debug($"Queue {queueName} doesn't exist, creating it");
					queueCreator.Options.EnableDelayedProcessing = true;
					queueCreator.Options.EnableHeartBeat = true;
					queueCreator.Options.EnableMessageExpiration = true;
					queueCreator.Options.EnableStatus = true;
					queueCreator.Options.EnableStatusTable = true;
					var result = queueCreator.CreateQueue();
					Logger.Debug(result.Status.ToString());
				}
```

**Comment by blehnen** [comment]
That should be all that's required.  Which transport are you using ?

**Comment by tmcque9** [comment]
I'm using SQLite.  I just realized that I probably needed to recreate the queues in the database, so I deleted it and let the program recreate it.  I'm testing now.

**Comment by tmcque9** [comment]
No luck.  I deleted the sqlite db file and let it be recreated from scratch, but I'm not getting the 2 minute delay I expect.

**Comment by tmcque9** [comment]
Here's the queue setup:

```
var container = new QueueContainer<SqLiteMessageQueueInit>();
var schedulerContainer = new SchedulerContainer();
var scheduler = schedulerContainer.CreateTaskScheduler();
taskFactory = schedulerContainer.CreateTaskFactory(scheduler);
taskFactory.Scheduler.Configuration.MaximumThreads = Config.MessageQueue.SchedulerMaxThreads;
taskFactory.Scheduler.Start();

AsyncMessageQueue<T> queue;

using (var queueCreator = queueCreationcontainer.GetQueueCreation<SqLiteMessageQueueCreation>(queueName, connectionString))
{
	Logger.Debug($"Checking to see if queue {queueName} exists");
	if (!(queueCreator.QueueExists))
	{
		Logger.Debug($"Queue {queueName} doesn't exist, creating it");
		queueCreator.Options.EnableDelayedProcessing = true;
		queueCreator.Options.EnableHeartBeat = true;
		queueCreator.Options.EnableMessageExpiration = true;
		queueCreator.Options.EnableStatus = true;
		queueCreator.Options.EnableStatusTable = true;
		var result = queueCreator.CreateQueue();
		Logger.Debug(result.Status.ToString());
	}

	queue = new AsyncMessageQueue<T>
	{
		producer = container.CreateProducer<T>(queueName, connectionString),
		consumer = container.CreateConsumerQueueScheduler(queueName, connectionString, taskFactory)
	};

	queue.producer.Configuration.TimeConfiguration.RefreshTime = TimeSpan.FromMinutes(Config.MessageQueue.RefreshTime);
	queue.consumer.Configuration.TimeConfiguration.RefreshTime = TimeSpan.FromMinutes(Config.MessageQueue.RefreshTime);
	queue.consumer.Configuration.Worker.TimeToWaitForWorkersToCancel = TimeSpan.FromSeconds(10);
	queue.consumer.Configuration.Worker.WorkerCount = Config.MessageQueue.WorkerMaxThreads;
}
```

and AsyncMessageQueue<T> is
```
public class AsyncMessageQueue<T> where T : class
{
	public IProducerQueue<T> producer { get; set; }
	public IConsumerQueueScheduler consumer { get; set; }

	public void Start(Action<T> messageHandler)
	{
		this.consumer.Start<T>((m, n) => messageHandler(m.Body));
	}

	public void Stop()
	{
		producer.Dispose();
		consumer.Dispose();
	}

	public void Send(T message, AdditionalMessageData data = null)
	{
		this.producer.Send(message, data);
	}

	public async Task SendAsync(T message, AdditionalMessageData data = null)
	{
		await this.producer.SendAsync(message, data);
	}
}
```

then it would be used like:

```
queue.Start(async (someObject) => someObjectHandler(someObject));

var data = new AdditionalMessageData();
data.SetDelay(TimeSpan.FromSeconds(120));
queue.SendAsync(someObject, data);

async Task someObjectHandler(SomeObject someObject)
{
    doStuff(someObject);
}
```

**Comment by blehnen** [comment]
To rule out the field not existing, if you open up your db3 file, does the MetaData table contain the column 'QueueProcessTime'?

The samples project didn't contain a sample for delayed processing.  I modified it so that it now does.  I'm seeing the behavior I expect from Sqlite when using delays of 10 or 30 seconds.  

That being said, I don't see anything wrong with your code above.  Does it process the record pretty much instantly?

**Comment by tmcque9** [comment]
Yes, the field exists in the database, and yes, the record processes within 1-2 seconds of hitting the queue.

**Comment by blehnen** [comment]
For 'data.SetDelay(x)', your using the SQLite extension method, and not the in-memory queue extension method?  They set the data in different locations, so that would cause SetDelay to do nothing, if it happens to be the wrong one.

**Comment by tmcque9** [comment]
That was it!

I had
``using DotNetWorkQueue.Transport.Memory;``

instead of
``using DotNetWorkQueue.Transport.SQLite.Shared;``

**Comment by blehnen** [comment]
Well, that's way too easy to accidentally do.  

I'll consider naming these extensions to be transport specific, though it would be a minor breaking change.  Or at least re-naming the in-memory one, as it's always present.

**Comment by tmcque9** [comment]
While I have your attention, how difficult would it be to add SQL CE 4 as a transport?

**Comment by blehnen** [comment]
Its similar enough to SQLite that it would not be a ton of effort - I'm curious though, what does it give you that SQLite does not?

**Comment by tmcque9** [comment]
Sorry it's taken so long to get back.  Everything I've found is that SQL CE 4.0 is more performant than SqLite, and I'm wondering if SQL CE would handle multiple threads better.

**Comment by blehnen** [comment]
Ah i see.  It might; I'm not sure either.  

My plan - though I have no idea when I will get to it, was to add a transport for [LiteDB](https://github.com/mbdavid/LiteDB).  The idea being, that would give the queue a local data store that no longer depends on unmanaged code.  Plus, the LiteDB benchmarks indicate that it does outperform SqLite generally speaking.

**Comment by tmcque9** [comment]
I'd like to contribute to that effort, if I can.
