### ISSUE TITLE
Unhanded system exception Newtonsoft.Json.JsonSerializationException: Error resolving type specified in JSON 'DotNetWorkQueue.ValueTypeWrapper`1[[System.DateTime, System.Private.CoreLib]]

### ISSUE THREAD

**Issue by darren-harris** [blehnen/DotNetWorkQueue#12]
I am trying to use the Framework with both .NET Core 3.1 and .NET Framework 4.7.2 consumers where each component has a different queue.  

The producer that generates work is in written in .NET Core 3.1.

When consuming the messages in a .NET Framework 4.7.2 process that have been generated by the .NET Core process, I get the following exception:

18:46:51 ERR] Unhanded system exception
Newtonsoft.Json.JsonSerializationException: Error resolving type specified in JSON 'DotNetWorkQueue.ValueTypeWrapper`1[[System.DateTime, System.Private.CoreLib]], DotNetWorkQueue'. Path 'Queue-FirstPossibleDeliveryDate.$type', line 1, position 140. ---> Newtonsoft.Json.JsonSerializationException: Could not find type 'DotNetWorkQueue.ValueTypeWrapper`1[[System.DateTime, System.Private.CoreLib]]' in assembly 'DotNetWorkQueue, Version=0.4.5.0, Culture=neutral, PublicKeyToken=null'. ---> Newtonsoft.Json.JsonSerializationException: Could not load assembly 'System.Private.CoreLib'.
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeFromTypeNameKey(StructMultiKey`2 typeNameKey)

This exception is caused by a difference in the value type for the "Queue-FirstPossibleDeliveryDate" that is stored in the message Header, that is different between runtimes:

Namely: 

"Queue-FirstPossibleDeliveryDate": {
    "$type": "DotNetWorkQueue.ValueTypeWrapper`1[[System.DateTime, System.Private.CoreLib]], DotNetWorkQueue",
    "Value": "2020-08-11T15:39:19.5178914Z"
  },

 "Queue-FirstPossibleDeliveryDate": {
    "$type": "DotNetWorkQueue.ValueTypeWrapper`1[[System.DateTime, mscorlib]], DotNetWorkQueue",
    "Value": "2020-08-12T07:52:19.3955732Z"
  },

I doubt that this mode of operation is supported, however we're migrating a set of code from .NET Framework to Core where we're using the Queue as a decoupling pattern and we're not yet in a place to migrate the whole system into Core in one go..  Is it possible to customise the serialisation of the header?

**Comment by blehnen** [comment]
Hi,

Well, this is a tricky one.  Yes, you can customize the serialization for the headers, though the same serializer is also used for the Linq tree. 

You would want to implement "IInternalSerializer", and then inject that into your queue container.  That will replace the built in one.  See "JsonSerializerInternal" for the internal implementation as a guide.

**Comment by darren-harris** [comment]
Hi,

Many thanks for the quick response! 

We actually found a work around that was localised to just the .NET framework processes. It's not "pretty" but it does work..

We added a new AssemblyResolver to the Current AppDomain

 AppDomain currentDomain = AppDomain.CurrentDomain;
     currentDomain.AssemblyResolve += new ResolveEventHandler(MyResolveEventHandler);

The add this function, which returns null for everything except the corelib type:

 private static Assembly MyResolveEventHandler(object sender, ResolveEventArgs args)
        {
            if (args.Name == "System.Private.CoreLib")
            {
                return typeof(DateTime).Assembly;
            }
            else
            {
                return null;
            }
        }

It's a transitory hack so happy to do this at the moment..

Thanks again..
D

**Comment by blehnen** [comment]
Hi,

Ah yes that's much simpler.
