### ISSUE TITLE
[SqlLite, .NET5]: RuntimeBinderException: 'System.MulticastDelegate' does not contain a definition for 'Invoke'

### ISSUE THREAD

**Issue by dlidstrom** [blehnen/DotNetWorkQueue#18]
I tried a simple example by following the guide for SqlLite. However, it throws an exception:

<details>
Debug    [Local] server difference is -0,0006 MS
Debug    [Local] server difference is -0,0001 MS
Debug    Worker 1 created
Information    Initializing with 1 workers
Information    Queue started
Processing messages - press any key to stop
Information    Scheduler time is 2021-09-21 11:35:16
Information    Local time is 2021-09-21 11:35:16
Debug    Worker 1 created
Information    Initializing with 1 workers
Information    Queue started
Error    Message with ID 8 has failed and has been moved to the error queue
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'System.MulticastDelegate' does not contain a definition for 'Invoke'
   at CallSite.Target(Closure , CallSite , Object , Object , IWorkerNotification )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at DotNetWorkQueue.Messages.MessageHandler.Handle(IReceivedMessageInternal message, IWorkerNotification workerNotification) in C:\Git\DotNetWorkQueue\Source\DotNetWorkQueue\Messages\MessageHandler.cs:line 48
   at DotNetWorkQueue.Metrics.Decorator.MessageHandlerDecorator.Handle(IReceivedMessageInternal message, IWorkerNotification workerNotification) in C:\Git\DotNetWorkQueue\Source\DotNetWorkQueue\Metrics\Decorator\IMessageHandlerDecorator.cs:line 50
   at DotNetWorkQueue.Trace.Decorator.MessageHandlerDecorator.Handle(IReceivedMessageInternal message, IWorkerNotification workerNotification) in C:\Git\DotNetWorkQueue\Source\DotNetWorkQueue\Trace\Decorator\MessageHandlerDecorator.cs:line 54
   at DotNetWorkQueue.Messages.HandleMessage.Handle(IReceivedMessageInternal message, IWorkerNotification workerNotification) in C:\Git\DotNetWorkQueue\Source\DotNetWorkQueue\Messages\HandleMessage.cs:line 57
   at DotNetWorkQueue.Queue.ProcessMessage.Handle(IMessageContext context, IReceivedMessageInternal transportMessage) in C:\Git\DotNetWorkQueue\Source\DotNetWorkQueue\Queue\ProcessMessage.cs:line 69
Debug    Stopping worker thread Worker 1
Debug    Stopping worker thread Worker 1
</details>

Here's the code sample to reproduce:

```csharp
using System;
using DotNetWorkQueue;
using DotNetWorkQueue.Configuration;
using DotNetWorkQueue.Logging;
using DotNetWorkQueue.Transport.SQLite.Basic;

namespace ConsoleTest
{
    internal class Program
    {
        private static readonly string connectionString = @"Data Source=c:\temp\queue.db;Version=3;";
        private static readonly string queueName = "testing";
        private static readonly QueueConnection queueConnection = new(queueName, connectionString);

        private static void Main()
        {
            try
            {
                CreateQueue();
                Send();

                using QueueContainer<SqLiteMessageQueueInit> queueContainer = new();
                using IConsumerQueue queue = queueContainer.CreateConsumer(queueConnection);
                queue.Start<SimpleMessage>(HandleMessages);
                Console.WriteLine("Processing messages - press any key to stop");
                _ = Console.ReadKey(true);

                static void HandleMessages(
                    IReceivedMessage<SimpleMessage> message,
                    IWorkerNotification notifications)
                {
                    notifications.Log.LogInformation($"start transaction {message.CorrelationId}");
                    notifications.Log.LogInformation($"received {message.MessageId}");
                    LogEntry entry = new(
                        LoggingEventType.Debug,
                        $"Processing Message {message.Body.Message}");
                    notifications.Log.Log(entry);
                    notifications.Log.LogInformation($"end transaction {message.CorrelationId}");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }

        private static void Send()
        {
            using QueueContainer<SqLiteMessageQueueInit> queueContainer = new();
            using IProducerQueue<SimpleMessage> queue = queueContainer.CreateProducer<SimpleMessage>(queueConnection);
            IQueueOutputMessage output = queue.Send(new SimpleMessage { Message = "Hello World" });
        }

        private static void CreateQueue()
        {
            // Create the queue if it doesn't exist
            QueueCreationContainer<SqLiteMessageQueueInit> createQueueContainer = new();
            SqLiteMessageQueueCreation queueCreation = createQueueContainer.GetQueueCreation<SqLiteMessageQueueCreation>(queueConnection);
            if (!queueCreation.QueueExists)
            {
                _ = queueCreation.CreateQueue();
            }
        }
    }
}
```

**Comment by dlidstrom** [comment]
Ok, that's interesting. My version of the class looks like this:

```csharp
namespace ConsoleTest
{
    internal class SimpleMessage
    {
        public string Message { get; set; }
    }
}
```

**Comment by blehnen** [comment]
The fix for using non-public message classes is a bit tricky (structure wise), though possible.   I might make this change in a future release.

For now, I've changed the producer to explicitly throw an exception if the message isn't a public class.
