### ISSUE TITLE
.Net Standard support?

### ISSUE THREAD

**Issue by wind-rider** [blehnen/DotNetWorkQueue#2]
This looks like a promising library!

Are there any plans to support .Net standard / .Net core?

**Comment by blehnen** [comment]
At the moment, no. I would need all of the 3rd party libraries I use to also support .net core.  I haven't checked in a while, but I think a few of them haven't updated yet.  Though I think the PostGre driver was updated to support .net core a couple of months ago.

I'm currently using this library as a plug-in to a legacy system that runs on the full framework, so I don't have a major need to support .net core.  However, that might change at some point.

**Comment by blehnen** [comment]
.Net standard 2.0 is now supported in 0.2.1, with the exception of the implementation of the metrics library. That library does not support .net standard yet.
