### ISSUE TITLE
OpenTelemetry 1.1.0 dependency issues with NET6

### ISSUE THREAD

**Issue by Charmedme** [blehnen/DotNetWorkQueue#23]
Hi, is it possible you could update OpenTelemetry to the latest version.
The current version has some issues with Microsoft.Extensions.Logging 6.0.0 as it's dependency is < 6.0.0.

We managed to work around the issue, but it would be nice if the dep of this project gets updated.

**Comment by blehnen** [comment]
Yeah, easy enough.  The tests all passed, so I've pushed out version 0.6.7 to nuget.
