### ISSUE TITLE
How to create tables beforehand?

### ISSUE THREAD

**Issue by cocowalla** [blehnen/DotNetWorkQueue#41]
Hi! For security reasons, my app doesn't have access to make schema changes, therefore something I'd like to do is create the required database tables as part of my schema migration process, rather than using `CreateQueue()`.

What would be the recommended way to obtain the required DLL please?

**Comment by cocowalla** [comment]
I'm looking to add the tables via our existing process (SQL scripts), but I was looking for a way to get the tables via code in order to do that.

As a workaround while playing with this library, what I did was as you suggest, run it locally and export the tables to SQL.

**Comment by blehnen** [comment]
Ah alright.  So, there is no direct way to obtain the script itself.  

However, it's created by this class here (assuming SQL server)

https://github.com/blehnen/DotNetWorkQueue/blob/master/Source/DotNetWorkQueue.Transport.SqlServer/Basic/SQLServerMessageQueueSchema.cs

If you create an instance of this class (will be a bit tricky, as you need to pass in the 3 deps that is requires), you can then ask it for the data directly via <instance>.GetSchema()

I could probably expose the script as part of the creation process in the future;  I would need to think about that a bit, as for instance - the Redis transport doesn't actually create a script internally.  Its a 'noop', as Redis creates structures on demand.

**Comment by cocowalla** [comment]
Thanks, I'll try the `SQLServerMessageQueueSchema` route.

> I could probably expose the script as part of the creation process in the future

Perhaps it would be part of a completely separate "admin API"?

**Comment by blehnen** [comment]
0.7.1 now allows obtaining the creation script from the IQueueCreation implementation via the property CreationScript
